### ISSUE TITLE
Issue #201: !selfmute and !mute do not unmute after expected time period

### ISSUE THREAD

**Issue by JC01010** [cbrxyz/pi-bot#201]
After expected time, pi-bot does not unmute.

**Comment by Nydauron** [comment]
Looked into it earlier today. For me at least, the issue seems to be coming from [line 175](https://github.com/cbrxyz/pi-bot/blob/22c5ea436f8d778056d2586b0a3bd58efb3cb5ef/bot.py#L175) where `member = None` and thus not having property `remove_roles`. Not exactly sure why `get_member` is returning `None` ...

Regardless, once a crono event has passed, it is always gets removed so they should repeat twice. Also, `remove_roles` and `add_roles` should not throw errors if roles were manually removed or added.

**Comment by Nydauron** [comment]
What's weird is that the latest master seems fine as of right now... Will see if it's a local thing ...

**Comment by cbrxyz** [comment]
This is because of issues with the cron list getting stuck on tasks
