### ISSUE TITLE
Kick unconfirmed users if they do not show activity within 3 days

### ISSUE THREAD

**Issue by cbrxyz** [cbrxyz/pi-bot#80]
If unconfirmed users do not show activity for 3 days, they should be kicked.

**Comment by cbrxyz** [comment]
Additionally, send them a message one day before they are kicked to alert them that they will be kicked

**Comment by Nydauron** [comment]
The first idea can probably be achieved by simply using `prune_members`, which can be set to a task to run, say, every 6 hours. Unfortunately, the second is a bit more complicated and would require querying for all the unconfirmed users and searching the `joined_at` property to determine if it's been at least 2 days since they joined.

**Comment by cbrxyz** [comment]
I re-talked over this with staff, and we feel this issue can be closed. Thanks for the thoughts!
